name: tylermaya
favicon: null
layout_spectrum: 0.03845958900637925
typography_spectrum: 0.7491381668951362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8677627206780016
  lightness: 0.6425349770579487
  saturation: 0.23555821203626692
  rhythmicContrast: 0.38297535688616335
purpose: []
